### ISSUE TITLE
can i transform function defined by pytorch in TensorFlow

### ISSUE THREAD

**Issue by mmmmayi** [BlackHC/tfpyth#1]
can i use function defined in pytorch, such as nn.Conv2d inTensorFlow? or just operation?

**Comment by BlackHC** [comment]
You just have to wrap calling it into a lambda ala:

```
conv = nn.Conv2d(...)

conv_as_tf_op = tensorflow_from_torch(lambda input: conv(input), ...)
```

See https://github.com/BlackHC/tfpyth/blob/master/tests/test_adapters.py for more examples.
